### ISSUE TITLE
PriorityQueue; TypeError: '<' not supported between instances of 'dict' and 'dict'

### ISSUE THREAD

**Issue by HWiese1980** [aio-libs/janus#199]
I'm trying to use the `PriorityQueue` in my program. 

I'm trying to store objects in the queue like this:

```
p = janus.PriorityQueue(loop=asyncio.get_event_loop(), maxsize=5)

p.sync_q.put((0, {"name": "test1"}))
p.sync_q.put((0, {"name": "test2"}))
```

And it results in 

```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/hybrit_py3_2/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-41389a2f4052>", line 1, in <module>
    p.sync_q.put((0, {"name": "test2"}))
  File "/home/user/anaconda3/envs/hybrit_py3_2/lib/python3.7/site-packages/janus/__init__.py", line 287, in put
    self._parent._put_internal(item)
  File "/home/user/anaconda3/envs/hybrit_py3_2/lib/python3.7/site-packages/janus/__init__.py", line 115, in _put_internal
    self._put(item)
  File "/home/user/anaconda3/envs/hybrit_py3_2/lib/python3.7/site-packages/janus/__init__.py", line 531, in _put
    heappush(self._queue, item)
TypeError: '<' not supported between instances of 'dict' and 'dict'
```

It seems like `heapq` wants to compare the items in the case that the priority value is the same, and fails because there's no such thing as `dict < dict`.

How do I store complex data types in a your PriorityQueue?

**Comment by asvetlov** [comment]
Sorry for the late reply.
Yes, the priority queue requires that pushed objects are comparable. `dict` is not.

The same limitation exists for standard [queue.PriorityQueue](https://docs.python.org/3/library/queue.html#queue.PriorityQueue). Any receipt that works for stdlib works for janus as well.

**Comment by dgtlmoon** [comment]
> Yes, the priority queue requires that pushed objects are comparable. `dict` is not.

Why? I understand that `priority` should be comparable, but why the object/dict ?
