### ISSUE TITLE
Make loop.close() and loop.is_closed() thread-safe

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/janus#2]
Sometimes we may get race collision on loop closing,
`queue.close()` and `queue.wait_closed()` doesn't help.

**Comment by asvetlov** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.4/asyncio/futures.py", line 408, in <lambda>
    new_future._copy_state, future))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 462, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 436, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 265, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

It appears **after** check for loop close on `.call_soon_threadsafe()` call but **before** actual `.call_soon()` call from `ThreadPoolExecutor`.

**Comment by ghostsquad** [comment]
As far as I can tell, this is because the `loop.is_closed()` is not threadsafe.

https://github.com/aio-libs/janus/blob/master/janus/__init__.py#L49

To solve this problem, you might need a threadsafe implementation of the loop, then with that you could do:

```Python
with loop.lock():
    if not loop.is_closed():
        loop.call_soon_threadsafe()
```

**Comment by asvetlov** [comment]
Agree with `RuntimeError` swallowing.
Would you create a Pull Request?

**Comment by asvetlov** [comment]
I think yes.
The issue is minor but annoying
