### ISSUE TITLE
Error with Python 3.10: "ValueError: loop argument must agree with lock"

### ISSUE THREAD

**Issue by simonw** [aio-libs/janus#358]
I ran into this in my own project, see https://github.com/simonw/datasette/pull/1481 - then I tried using a fork of this project to run the unit tests against Python 3.10 and got the same error: https://github.com/simonw/janus/runs/3842463703?check_suite_focus=true

```
2021-10-08T20:01:29.1812342Z ============================= test session starts ==============================
2021-10-08T20:01:29.1814198Z platform linux -- Python 3.10.0, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
2021-10-08T20:01:29.1815193Z rootdir: /home/runner/work/janus/janus
2021-10-08T20:01:29.1816205Z plugins: cov-2.12.1, asyncio-0.15.1
2021-10-08T20:01:29.1816927Z collected 72 items
2021-10-08T20:01:29.1817337Z 
2021-10-08T20:01:30.7135535Z tests/test_async.py FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                      [ 43%]
2021-10-08T20:01:31.4033885Z tests/test_mixed.py .FFFFFFFFFFFFFFFFF                                   [ 68%]
2021-10-08T20:01:32.7430231Z tests/test_sync.py FFFFFFFFFFFFFFFFFFFFFFF                               [100%]
2021-10-08T20:01:32.7431283Z 
2021-10-08T20:01:32.7432062Z =================================== FAILURES ===================================
2021-10-08T20:01:32.7433223Z __________________________ TestQueueBasic.test_empty ___________________________
2021-10-08T20:01:32.7434042Z 
2021-10-08T20:01:32.7442019Z self = <test_async.TestQueueBasic object at 0x7fb0f561e4d0>
2021-10-08T20:01:32.7442978Z 
2021-10-08T20:01:32.7443802Z     @pytest.mark.asyncio
2021-10-08T20:01:32.7444813Z     async def test_empty(self):
2021-10-08T20:01:32.7445688Z >       _q = janus.Queue()
2021-10-08T20:01:32.7446250Z 
2021-10-08T20:01:32.7446977Z tests/test_async.py:65: 
2021-10-08T20:01:32.7447841Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2021-10-08T20:01:32.7448693Z janus/__init__.py:39: in __init__
2021-10-08T20:01:32.7454061Z     self._async_not_empty = asyncio.Condition(self._async_mutex)
2021-10-08T20:01:32.7455609Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2021-10-08T20:01:32.7456149Z 
2021-10-08T20:01:32.7458604Z self = <[AttributeError("'Condition' object has no attribute 'locked'") raised in repr()] Condition object at 0x7fb0f569a620>
2021-10-08T20:01:32.7459706Z lock = <asyncio.locks.Lock object at 0x7fb0f569ada0 [unlocked]>
2021-10-08T20:01:32.7460382Z 
2021-10-08T20:01:32.7460904Z     def __init__(self, lock=None, *, loop=mixins._marker):
2021-10-08T20:01:32.7461507Z         super().__init__(loop=loop)
2021-10-08T20:01:32.7461997Z         if lock is None:
2021-10-08T20:01:32.7462421Z             lock = Lock()
2021-10-08T20:01:32.7462944Z         elif lock._loop is not self._get_loop():
2021-10-08T20:01:32.7463634Z >           raise ValueError("loop argument must agree with lock")
2021-10-08T20:01:32.7466985Z E           ValueError: loop argument must agree with lock
```

**Comment by simonw** [comment]
The code involved here is the `Queue` constructor: https://github.com/aio-libs/janus/blob/d7970f8b76bcac2e087067ca4575ac845e481874/janus/__init__.py#L24-L42

**Comment by simonw** [comment]
In particular it seems to be these two lines:  https://github.com/aio-libs/janus/blob/d7970f8b76bcac2e087067ca4575ac845e481874/janus/__init__.py#L38-L39

I don't understand how those are any different from doing this: `asyncio.Condition(asyncio.Lock())` - which works fine when I try it in the Python 3.10 interpreter:

```
~ % /Users/simon/.pyenv/versions/3.10.0/bin/python
Python 3.10.0 (default, Oct  7 2021, 13:45:58) [Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> asyncio.Condition(asyncio.Lock())
<asyncio.locks.Condition object at 0x10ace2110 [unlocked]>
```

**Comment by simonw** [comment]
Aha! But that simple `asyncio.Condition(asyncio.Lock())` line DOES fail if it runs inside an event loop:
```pycon
>>> async def run():
...     print(asyncio.Condition(asyncio.Lock()))
... 
>>> asyncio.run(run())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/simon/.pyenv/versions/3.10.0/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/simon/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "<stdin>", line 2, in run
  File "/Users/simon/.pyenv/versions/3.10.0/lib/python3.10/asyncio/locks.py", line 234, in __init__
    raise ValueError("loop argument must agree with lock")
ValueError: loop argument must agree with lock
```

**Comment by simonw** [comment]
That addressed the bug!

```
(janus) janus % pytest -x      
============================================================= test session starts ==============================================================
platform darwin -- Python 3.10.0, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/simon/Dropbox/Development/janus
plugins: cov-2.12.1, asyncio-0.15.1
collected 72 items                                                                                                                             

tests/test_async.py ...............................                                                                                      [ 43%]
tests/test_mixed.py ..................                                                                                                   [ 68%]
tests/test_sync.py .......................                                                                                               [100%]

============================================================== 72 passed in 5.34s ==============================================================
```

**Comment by achimnol** [comment]
I have sent a PR to CPython: python/cpython#28850.

**Comment by StanleyAbotsikuma** [comment]
i have same error with django channels
